
package com.phonebook;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;

public class PdfGeneration {
    
    public void pdfGenerator(String fileName, String content) {
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(fileName + ".pdf"));
            document.open();
            Image image = Image.getInstance(getClass().getResource("telefonkonyv.jpg"));
            image.scaleToFit(400, 200);
            image.setAbsolutePosition(120f, 625f);
            document.add(image);
            
            document.add(new Paragraph("\n\n\n\n\n\n\n\n\n\n\n" + content, FontFactory.getFont("betutipus", BaseFont.IDENTITY_H, BaseFont.EMBEDDED)));
            Chunk signature = new Chunk("\n\n Generated by Phone book app!");
            
            Paragraph base = new Paragraph(signature);
            document.add(base);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        document.close();
    }
    
}
